# Site settings
title: Dominik Petrovic
#twitter_username: rob_hinds
name: Dominik Petrovic

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://nixxcode.com/blog
 - title: GitHub
   url: https://github.com/nixxcode
 - title: LinkedIn
   url: https://www.linkedin.com/in/dominik-petrovic-15938b55/

#Any buzzword skills you want to include
skills:
 - Java
 - Kotlin
 - Maven
 - Maven central publishing
 - Gradle
 - Java JNI
 - Cross-platform publishing
 - SQL
 - REST API
 - HTTP
 - Web
 - HTML
 - JavaScript
 - Git
 - GitHub

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Career Break
   start: 2018
   end: Ongoing
   employer: Unemployed
   description: The career break was necessary for personal (family-related) reasons. I took the opportunity to consider the professional direction I wish to take. During this time, I have been contributing to open source projects to build my skills and keep them sharp.<br/><br/> My circumstances have changed, and I am fully ready to commit myself to a professional life again. I am also very excited about starting a new career as a professional software developer!  
 - title: IT Support Assistant
   start: 2017
   end: 2018
   employer: Britpart
   description: My role at Britpart involved maintaining and troubleshooting a network of over 300 devices (PCs, laptops, tablets, printers, etc) both physically, as well as via Active Directory on Windows Server 2012. I also implemented a custom e-mail signature solution (called Exclaimer) for Microsoft Outlook across their entire business network.
 - title: 2nd Line Support Analyst
   start: 2015
   end: 2016
   employer: Guestline Ltd
   description: My role at Guestline involved offering advanced second line technical support for the company's software solutions to business customers via telephone, e-mail and remote desktop connections. It was a busy role where meeting SLA targets was critical.
 - title: Freelance IT Pro
   start: 2012
   end: 2015
   employer: Self-employed
   description: Assisting home and small business users with common IT problems such as OS installation, LAN setup, hardware repairs, virus removal, software installation, backups, security, etc. 
 - title: Bachelor of Science (B.Sc.)
   start: 2007
   end: 2012
   employer: University of Maribor, Faculty of Electrical Engineering and Computer Science<br/>2007 - 2012 

#Education is required
#education:
# - level: Bachelor of Science (B.Sc.)
#   date: 2002
#   subject: IT and Computer Science
#   school: University of Mariboer, Faculty of Electrical Engineering and Computer Science, Slovenia

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - nixxcode/jvm-brotli
 - nixxcode/nixxcode.github.io
 - tipsy/javalin

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: http://stackoverflow.com/users/258813/rhinds
#   flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
  Hello, my name is Dominik. I currently reside in Shrewsbury, United Kingdom. I am actively seeking employment as a software engineer.<br/><br/>
  
  I am a tech enthusiast with a passion for open source projects. I fell in love with software development when I tried my hand at modding the game Minecraft, and have been aspiring to become a professional developer ever since.<br/><br/>
  
  While it's true I don't have any experience as a commercial developer, I am definitely not a stranger to technology. I have a Bachelor's degree in computer science, coupled with a rich set of technical skills and experiences from previous employment.<br/><br/>
  
  To demonstrate my skills and competencies, I invite you to have a look at my employment history (click the individual year bubbles for more information), as well as the open source projects I am involved with. You can also find a link to my Github profile in the top navigation bar<br/><br/>
  
  If you wish to get in touch, please contact me at dominik.petrovic87@gmail.com, thank you.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="http://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="http://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
